name: CoreX2
main: sakura\core
version: 1.4-beta
author: Codeeeh
api: [3.3.0, 3.2.0, 3.5.2]
load: POSTWORLD

commands:
  grant:
    description: FOR CONSOLE USE ONLY!
  takegem:
    description: FOR CONSOLE USE ONLY!
  sys:
    description: FOR CONSOLE USE ONLY!
  +:
    description: FOR CONSOLE USE ONLY!
  test:
    description: FOR CONSOLE USE ONLY!
  quest:
    description: Opens Quest menu
  cloud:
    description: < help / ? >
  givetitle:
    description: 
  mytitles:
    description: open title picker
