baseExp: 156

vault:
  price: 25000 #access price
  slots: 10 #initial slot
  upgrade:
    increase: 5
    price: 7000
    
top-signs-enabled?: false
top-signs-interval: 1
top-signs:
# world: [x:y:z]
  hub: [-29:81:-57:"level"]
